---
title: "Evol_mass_2012_2015"
author: "Martin Colomb"
date: "`r Sys.Date()`"
version: "R-4.4.2"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    theme: flatly
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Chargement des packages

```{r packages}
library(dplyr)
library(ggplot2)
library(lubridate)
library(ncdf4)
library(stringr)
library(tibble)
library(writexl)


```

# Lecture des données

```{r cell-area}
chem_hist<-"C:/Users/colom/Desktop/STAGE/data/clean_mod_data/14_3_1"
statemet<-nc_open(file.path(chem_hist, "GEOSChem.StateMet.2014_2015_m.nc4"))


Met_AD<-ncvar_get(statemet, "Met_AD")  #Met_AD (Dry air mass kg)
mean_Met_AD <- apply(Met_AD, c(1,2,3), mean, na.rm = TRUE)


kg_Mg = 1e-3
MW_Hg = 200.59
avo = 6.02e23
g_kg = 1e-3
cm2_m2 = 1e4
M_Hg <- 0.20059
M_air <- 0.028964
```

# The conversion formula is:

```         
    mol species                g/mol species
    ----------- * kg dry air * -------------
    mol dry air                g/mol dry air

    = volume mixing ratio * dry air mass * MW species / MW dry air

    = kg species
    
        
    MW dry air is defined as 28.9644 g/mol
    https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/Headers/physconstants.F90#L26

    
    
```

```{r plot Hg total mensuel, echo=TRUE}

conc_2012_2015<-nc_open(file.path(chem_hist, "HIST_4y/GEOSChem.SpeciesConc.2012_2015_m.nc4"))
print(conc_2012_2015)
variable_names <- names(conc_2012_2015$var)
print(variable_names)
names(conc_2012_2015$dim)       # pour les dimensions

species_hg <- c(
  "SpeciesConcVV_HgClO", "SpeciesConcVV_HgBrO", "SpeciesConcVV_HgOHO",
  "SpeciesConcVV_PHg2Cl", "SpeciesConcVV_PHg2OH", "SpeciesConcVV_PHg2Br",
  "SpeciesConcVV_PHg0", "SpeciesConcVV_PHg2",
  "SpeciesConcVV_Hg2STRP", "SpeciesConcVV_Hg2ORGP", "SpeciesConcVV_Hg2ClP",
  "SpeciesConcVV_HgCl2", "SpeciesConcVV_HgOHOH", "SpeciesConcVV_HgOHBrO",
  "SpeciesConcVV_HgOHClO", "SpeciesConcVV_HgOHHO2", "SpeciesConcVV_HgOHNO2",
  "SpeciesConcVV_HgOH", "SpeciesConcVV_HgClOH", "SpeciesConcVV_HgClBr",
  "SpeciesConcVV_HgClBrO", "SpeciesConcVV_HgClClO", "SpeciesConcVV_HgClHO2",
  "SpeciesConcVV_HgClNO2", "SpeciesConcVV_HgCl", "SpeciesConcVV_HgBr2",
  "SpeciesConcVV_HgBrOH", "SpeciesConcVV_HgBrClO", "SpeciesConcVV_HgBrBrO",
  "SpeciesConcVV_HgBrHO2", "SpeciesConcVV_HgBrNO2", "SpeciesConcVV_HgBr",
  "SpeciesConcVV_Hg0"
)

# === 4. Calcul masse totale Hg ===
mass_total <- 0
for (sp in species_hg) {
  cat("Traitement de", sp, "...\n")
  
  conc <- ncvar_get(conc_2012_2015, sp)  # [lon, lat, lev, time]
  
  if (length(dim(conc)) == 4 && all(dim(conc)[1:3] == dim(mean_Met_AD))) {
    nt <- dim(conc)[4]
    for (t in 1:nt) {
      mass_Hg_t <- conc[,,,t] * mean_Met_AD * (M_Hg / M_air)  # kg
      mass_total <- mass_total + sum(mass_Hg_t, na.rm = TRUE)
    }
  } else {
    warning(paste("Dimensions incompatibles pour", sp))
  }
}

cat("\n💡 Masse totale de tout le Hg atmosphérique (2012–2015) :", format(mass_total, scientific = TRUE), "kg\n")

```



```{r plot}
# === 2. Temps (convertir temps GEOS-Chem en dates R) ===
time_vals <- ncvar_get(conc_2012_2015, "time")  # temps en heures depuis...
time_units <- ncatt_get(conc_2012_2015, "time", "units")$value

# Convertir les unités : "hours since 2012-01-01 00:00:00"
origin <- ymd_hms(sub("hours since ", "", time_units))
time_dates <- origin + hours(time_vals)

nt <- length(time_dates)
mass_by_month <- data.frame(date = time_dates, mass_kg = rep(0, nt))

# === 3. Calcul de la masse totale pour chaque timestep ===
for (sp in species_hg) {
  cat("Traitement de", sp, "...\n")
  conc <- ncvar_get(conc_2012_2015, sp)  # [lon, lat, lev, time]

  for (t in 1:nt) {
    mass_Hg_t <- conc[,,,t] * mean_Met_AD * (M_Hg / M_air)
    mass_by_month$mass_kg[t] <- mass_by_month$mass_kg[t] + sum(mass_Hg_t, na.rm = TRUE)
  }
}

# === 4. Agrégation par mois ===
mass_monthly <- mass_by_month %>%
  mutate(month = floor_date(date, "month")) %>%
  group_by(month) %>%
  summarise(total_mass_kg = sum(mass_kg, na.rm = TRUE))

# === 5. Plot ===
ggplot(mass_monthly, aes(x = month, y = total_mass_kg / 1e6)) +  # en mégagrammes (tonnes)
  geom_line(color = "darkblue") +
  labs(
    title = "Évolution mensuelle de la masse totale de mercure atmosphérique",
    x = "Date",
    y = "Masse totale de Hg (tonnes)",
    caption = "Calculé à partir de toutes les espèces Hg GEOS-Chem"
  ) +
  theme_classic(base_size = 14) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.8)
  )





```